ulwt:
  embed_dim: 512
  n_layers: 8
  n_heads: 8
  dropout: 0.1
  max_len: 128
  reward_bins: 15

# Training hyperparameters
training:
  batch_size: 16
  num_epochs: 3
  w_hfp: 0.1
  loss_weights:
    hfp_bce: 1.0 